replicaCount: 2
image:
  tag: 1.0.2

service:
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 500M
  limits:
    cpu: 200m
    memory: 500M

namespace: torino
db:
  url: scheduler-db-mysql.torino-db.svc.cluster.local
  port: 3306
  password: welcome
  username: root

central:
  host: torino-central-server
  port: 8500