apiVersion: apps/v1
kind: Deployment
metadata:
  name: torino-fetcher
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "guojiaqi1027/torino-fetcher:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: spring.config.location
              value: "/config/application.yaml,/config/log4j2.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.service.port}}
              protocol: TCP
          volumeMounts:
            - name: config-template
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-template
          configMap:
            name: {{ .Release.Name }}-application-configmap
